import { useEffect, useState } from "react";
import { Badge, Button, Card, EmptyState, Input, Toast } from "../../../components/index.js";
import { listAdminUsers, setAdminUserDisabled } from "../../../services/adminUsers.js";

export function AdminUsersPage() {
  const [users, setUsers] = useState([]), [search, setSearch] = useState(""), [loading, setLoading] = useState(true), [changing, setChanging] = useState(""), [toast, setToast] = useState("");
  useEffect(() => { refresh(""); }, []);
  async function refresh(query = search) { setLoading(true); try { setUsers((await listAdminUsers({ search: query })).users || []); } catch (error) { setToast(error.message || "Impossibile caricare gli utenti."); } finally { setLoading(false); } }
  async function toggle(user) { const disabled = !user.disabled; if (!confirm(`${disabled ? "Disabilitare" : "Riattivare"} ${user.email || user.uid}?`)) return; setChanging(user.uid); try { await setAdminUserDisabled(user.uid, disabled); setUsers((all) => all.map((item) => item.uid === user.uid ? { ...item, disabled } : item)); setToast(disabled ? "Account disabilitato; operazione registrata." : "Account riattivato; operazione registrata."); } catch (error) { setToast(error.message || "Modifica non riuscita."); } finally { setChanging(""); } }
  return <div className="admin-react-stack"><header className="admin-react-header"><div><span className="eyebrow">Clienti</span><h2>Utenti registrati</h2><p>Account, verifica email, attività e newsletter. Password, token e dati di pagamento non sono accessibili.</p></div></header><Card><form className="admin-users-search" onSubmit={(event) => { event.preventDefault(); refresh(); }}><Input aria-label="Cerca utenti" placeholder="Cerca email, nome o UID..." value={search} onChange={(event) => setSearch(event.target.value)} /><Button type="submit" disabled={loading}>{loading ? "Caricamento..." : "Cerca"}</Button></form></Card>{!loading && !users.length ? <EmptyState title="Nessun utente trovato" description="Prova con un’altra ricerca." /> : <div className="admin-users-list">{users.map((user) => <Card key={user.uid} className="admin-user-card"><div><div className="admin-user-heading"><strong>{user.displayName || user.email || "Utente"}</strong><Badge>{user.disabled ? "Disabilitato" : user.emailVerified ? "Verificato" : "Da verificare"}</Badge></div><small>{user.email || "Email non disponibile"}</small><dl><div><dt>Registrato</dt><dd>{date(user.createdAt)}</dd></div><div><dt>Ultimo accesso</dt><dd>{date(user.lastSignInAt)}</dd></div><div><dt>Ordini</dt><dd>{user.orderCount}</dd></div><div><dt>Newsletter</dt><dd>{user.newsletterStatus === "subscribed" ? "Iscritto" : "Non iscritto"}</dd></div></dl><details><summary>UID tecnico</summary><code>{user.uid}</code></details></div><Button variant={user.disabled ? "secondary" : "ghost"} disabled={changing === user.uid} onClick={() => toggle(user)}>{changing === user.uid ? "Aggiornamento..." : user.disabled ? "Riattiva" : "Disabilita"}</Button></Card>)}</div>}<Toast message={toast} /></div>;
}
function date(value) { return value ? new Intl.DateTimeFormat("it-IT", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Mai"; }
