import { useEffect, useMemo, useState } from "react";
import { Badge, Button, Card, EmptyState, Input } from "../components/index.js";
import { listCatalogOptions } from "../services/catalogOptions.js";

export function FragrancesPage({ onOpenHome }) {
  const [fragrances, setFragrances] = useState([]), [search, setSearch] = useState(""), [loading, setLoading] = useState(true);
  useEffect(() => {
    document.title = "Fragranze per candele personalizzate | DÈDICA";
    setMeta("description", "Scopri tutte le fragranze DÈDICA per candele personalizzate: note floreali, gourmand, legnose, fresche e marine.");
    listCatalogOptions().then(items => setFragrances(items.filter(item => item.type === "fragrance" && item.active !== false))).finally(() => setLoading(false));
    return () => { document.title = "DÈDICA — Candele personalizzate"; setMeta("description", "Candele personalizzate DÈDICA per regali, eventi e bomboniere: dedica, bozza digitale e confezione curata."); };
  }, []);
  const visible = useMemo(() => fragrances.filter(item => `${item.label} ${item.description}`.toLowerCase().includes(search.toLowerCase())), [fragrances, search]);
  useEffect(() => { const id = "fragrance-structured-data"; document.getElementById(id)?.remove(); if (!fragrances.length) return; const script = document.createElement("script"); script.id = id; script.type = "application/ld+json"; script.textContent = JSON.stringify({ "@context": "https://schema.org", "@type": "ItemList", name: "Fragranze DÈDICA", itemListElement: fragrances.map((item, index) => ({ "@type": "ListItem", position: index + 1, name: item.label, description: item.description })) }); document.head.appendChild(script); return () => script.remove(); }, [fragrances]);
  return <main className="fragrances-page"><section className="fragrances-hero"><div><Badge>Guida alle profumazioni</Badge><h1>Una fragranza per ogni ricordo.</h1><p>Fresche, fiorite, gourmand, legnose o marine: scopri le note delle candele DÈDICA e scegli quella che racconta meglio la tua dedica.</p><Button variant="secondary" onClick={onOpenHome}>Scopri le candele</Button></div><div className="fragrances-hero-notes" aria-hidden="true"><span>Fiorite</span><span>Legnose</span><span>Dolci</span><span>Fresche</span></div></section><section className="fragrances-catalog"><header><div><span className="eyebrow">La collezione olfattiva</span><h2>Tutte le fragranze</h2><p>{fragrances.length} profumazioni disponibili da abbinare ai prodotti selezionati.</p></div><Input type="search" aria-label="Cerca una fragranza" placeholder="Cerca note o fragranza..." value={search} onChange={event => setSearch(event.target.value)} /></header>{loading ? <EmptyState title="Caricamento fragranze" /> : visible.length ? <div className="fragrances-grid">{visible.map((item, index) => <Card key={item.id} className="fragrance-card"><span>{String(index + 1).padStart(2, "0")}</span><h2>{item.label}</h2><p>{item.description || "Descrizione in arrivo."}</p></Card>)}</div> : <EmptyState title="Nessuna fragranza trovata" description="Prova un termine diverso." />}</section><aside className="fragrances-note"><h2>Come scegliere?</h2><p>Pensa alla persona, alla stagione e all’ambiente. Nel configuratore trovi il pulsante Info accanto alle profumazioni disponibili per ciascuna candela.</p></aside></main>;
}
function setMeta(name, content) { let element = document.querySelector(`meta[name="${name}"]`); if (!element) { element = document.createElement("meta"); element.name = name; document.head.appendChild(element); } element.content = content; }
